version: '3.8'
services:
  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-logs:/var/log/nginx  
    depends_on:
      - php
      - db
    networks:
      - supermercado-net

  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    volumes:
      - ./:/var/www/html
      - ./php-logs:/var/log/php  
    depends_on:
      - db
    networks:
      - supermercado-net

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: SaludyBienestar
      POSTGRES_USER: martin
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres-logs:/var/log/postgresql  
    ports:
      - "5433:5432"
    networks:
      - supermercado-net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - supermercado-net

  logstash:
    image: docker.elastic.co/logstash/logstash:7.14.0
    volumes:
      - ./pipeline:/usr/share/logstash/pipeline  
      - ./nginx-logs:/var/log/nginx
      - ./php-logs:/var/log/php
      - ./postgres-logs:/var/log/postgresql
    environment:
      - "LS_JAVA_OPTS=-Xmx256m -Xms256m"
    depends_on:
      - elasticsearch
    networks:
      - supermercado-net

  kibana:
    image: docker.elastic.co/kibana/kibana:7.14.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - supermercado-net

  
  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:0.11.0
    command:
      - -nginx.scrape-uri=http://web:80/nginx_status
    depends_on:
      - web
    networks:
      - supermercado-net

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    environment:
      - DATA_SOURCE_NAME=postgresql://martin:1234@db:5432/SaludyBienestar?sslmode=disable
    networks:
      - supermercado-net

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      - supermercado-net
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    networks:
      - supermercado-net

networks:
  supermercado-net:
    driver: bridge

volumes:
  postgres_data:
  prometheus_data:
  grafana_data:
  elasticsearch_data: